; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-supermini]
platform  = espressif32
board     = esp32-c3-devkitm-1
framework = arduino

; Serial monitor baud rate
monitor_speed = 115200

; Add all include subfolders to compiler search path
; This lets every file write #include "fsm.h" instead of #include "core/fsm.h"
; Rule: when you add a new subfolder under include/, add a matching -I line here
build_flags =
    -I include/core
    -I include/ui
    -I include/i2c

; Libraries — PlatformIO downloads these automatically on first build
lib_deps =
    olikraus/U8g2@^2.35.7
